---
name: cratedb

releases:
- name: cratedb
  version: latest

stemcells:
- alias: ubuntu
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: crate 
  provides:
    peers: {as: crate}
  consumes:
    peers: {from: crate} 
  vm_extensions:
  - all_ports
  - crate
  instances: 3
  azs: [ z1 ]
  vm_type: default
  persistent_disk_type: default
  stemcell: ubuntu
  networks:
  - name: default
  jobs:
  - name: crate 
    release: cratedb
- name: crate_adapter
  consumes:
    peers: {from: crate}
  vm_extensions: 
  - all_ports
  instances: 1
  azs: [ z1 ]
  vm_type: default
  persistent_disk_type: default
  stemcell: ubuntu
  networks:
  - name: default
  jobs:
  - name: crate_adapter 
    release: cratedb
  properties:
    crate_adapter:
      dbhost: "172.16.1.13"
update:
  canaries: 1
  max_in_flight: 10
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
